name 'mojolingo-asterisk'
version '0.1.0'
source 'git://github.com/mojolingo/asterisk.git'
author 'Ben Klang'
license 'MIT'
summary 'Module for installing Asterisk'
description 'Sets up the Digium package repository where appropriate and ensures Asterisk packages are installed'
project_page 'https://github.com/mojolingo/puppet-asterisk'
#dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt', '>= 0.0.4'
